services:
  db:
    image: postgres:15
    container_name: racha-db
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: rachaapp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
